version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6.11
        environment:
          REACT_APP_APP_URL: https://app.backstroke.co
          REACT_APP_API_URL: https://api.backstroke.co
          REACT_APP_ROOT_URL: https://backstroke.co

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Install dependencies"
          command: yarn
      - run:
          name: "Make a build"
          command: yarn build
      - run:
          name: "Push to server"
          command: |
            sudo npm i -g surge
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              surge --project ./build --domain app.backstroke.co
            else
              surge --project ./build --domain app-backstroke-$CIRCLE_BRANCH.surge.sh
            fi
      - run:
          name: "Build container"
          command: docker build -t backstroke/dashboard:latest .
      - run:
          name: "Push container"
          command: docker push backstroke/dashboard:latest
